font:
  # The normal (roman) font face to use.
  normal:
    family: "FiraCode Nerd Font"
    #family: "Hack Nerd Font"
    # Style can be specified to pick a specific face.
    style: Bold
window:
  decorations: buttonless
background_opacity: 0.8
